# TODO: remove this file by either moving cops here or fixing code
inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.2
  TargetRailsVersion: 5.1
  Exclude:
    - 'Rakefile'

Rails:
  Enabled: true

# Don't enforce documentation
Style/Documentation:
  Enabled: false

Rails/ActionFilter:
  EnforcedStyle: action

Metrics/MethodLength:
  Max: 25

Style/Next:
  Enabled: false

# Support both ruby19 and hash_rockets
Style/HashSyntax:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'

Performance/FixedSize:
  Exclude:
    - 'test/**/*'

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'

Style/SymbolArray:
  Enabled: false

Lint/BooleanSymbol:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/LineLength:
  Max: 180

Style/FormatStringToken:
  Enabled: false
