require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-minitest

# TODO: remove this file by either moving cops here or fixing code
inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5
  TargetRailsVersion: 5.2
  Exclude:
    - 'extras/**/*'
    - 'locale/**/*'
    - 'node_modules/**/*'
    - 'vendor/bundle/**/*'

Rails:
  Enabled: true

# Don't enforce documentation
Style/Documentation:
  Enabled: false

Rails/ActionFilter:
  EnforcedStyle: action

Metrics:
  Enabled: false

Style/Next:
  Enabled: false

Layout/LineLength:
  Max: 180

# Support both ruby19 and hash_rockets
Style/HashSyntax:
  EnforcedStyle: no_mixed_keys

Performance/FixedSize:
  Exclude:
    - 'test/**/*'

Style/SymbolArray:
  Enabled: false

Lint/BooleanSymbol:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
